package de.hauschil.dbprojekt.controller;

public class Helper {
	public static final int FAKTOR 		= 50;
	public static final int ANZ_KUNDEN 	= 100 * FAKTOR;
	public static final int ANZ_PARTNER = FAKTOR;
	public static final int ANZ_ANRUFPM	= 3 * FAKTOR;
	
	public static String[] vornamen = {
		"Agnes", "Agnieszka", "Alexandra", "Alina", "Alma", "Amelie", "Andrea", 
		"Anett", "Anette", "Angela", "Angelica", "Angelika", "Anica", "Anika", 
		"Anita", "Anja", "Anke", "Ann", "Anna", "Anne", "Anneliese", 
		"Annemarie", "Annett", "Annette", "Anni", "Annica", "Annie", "Annika", 
		"Anny", "Antje", "Antonia", "Ariane", "Astrid", "Auguste", "Ayse", 
		"Bärbel", "Barbara", "Beata", "Beate", "Beatrice", "Berit", "Berta", 
		"Bertha", "Bettina", "Bianca", "Bianka", "Birgit", "Birgitt", "Birte", 
		"Birthe", "Brigitte", "Britta", "Caren", "Carina", "Carla", "Carmen", 
		"Carola", "Carolin", "Caroline", "Catarina", "Catharina", "Cathleen", "Cathrin", 
		"Catrin", "Celina", "Charlotte", "Christa", "Christel", "Christiane", "Christin", 
		"Christina", "Christine", "Cindy", "Clara", "Claudia", "Constanze", "Cordula", 
		"Corinna", "Cornelia", "Dörte", "Dörthe", "Dagmar", "Dana", "Daniela", 
		"Denise", "Diana", "Dora", "Doreen", "Doris", "Dorothea", "Dorothee", 
		"Edith", "Elena", "Elfriede", "Elisabeth", "Elise", "Elke", "Ella", 
		"Elli", "Elly", "Elsa", "Else", "Emilia", "Emilie", "Emily", 
		"Emine", "Emma", "Erika", "Erna", "Esther", "Eva", "Evelin", 
		"Eveline", "Evelyn", "Evelyne", "Ewa", "Fatma", "Filiz", "Franziska", 
		"Frauke", "Frida", "Frieda", "Friederike", "Gabi", "Gabriela", "Gabriele", 
		"Gaby", "Gerda", "Gertrud", "Gesa", "Gisela", "Grit", "Hanna", 
		"Hannah", "Hannelore", "Hatice", "Hedwig", "Heidi", "Heike", "Helena", 
		"Helene", "Helga", "Henni", "Henny", "Herta", "Hertha", "Hildegard", 
		"Ida", "Ilka", "Ilona", "Ilse", "Imke", "Ina", "Ines", 
		"Inga", "Inge", "Ingeborg", "Ingrid", "Irene", "Irina", "Iris", 
		"Irma", "Irmgard", "Isabel", "Isabell", "Isabella", "Isabelle", "Ivonne", 
		"Jacqueline", "Jana", "Janet", "Janett", "Janette", "Janin", "Janina", 
		"Janine", "Jaqueline", "Jasmin", "Jeanette", "Jeannette", "Jennifer", "Jenny", 
		"Jessica", "Jessika", "Joanna", "Johanna", "Judith", "Julia", "Juliane", 
		"Jutta", "Käte", "Käthe", "Karen", "Karin", "Karina", "Karla", 
		"Karola", "Karolin", "Karoline", "Katarina", "Katarzyna", "Katharina", "Kathi", 
		"Kathie", "Kathleen", "Kathrin", "Kati", "Katie", "Katja", "Katrin", 
		"Kerstin", "Kim", "Kirsten", "Kirstin", "Klara", "Klaudia", "Konstanze", 
		"Kordula", "Korinna", "Kornelia", "Kristiane", "Kristin", "Kristina", "Kristine", 
		"Lara", "Larissa", "Laura", "Lea", "Leah", "Lena", "Leni", 
		"Leoni", "Leonie", "Lidia", "Lieselotte", "Lili", "Lilli", "Lilly", 
		"Lina", "Linda", "Lisa", "Liselotte", "Lotte", "Louisa", "Louise", 
		"Luisa", "Luise", "Lydia", "Magdalena", "Maike", "Maja", "Malgorzata", 
		"Mandy", "Manja", "Manuela", "Mareike", "Maren", "Margarete", "Margarethe", 
		"Margot", "Margrit", "Maria", "Marianne", "Marie", "Marina", "Marion", 
		"Marta", "Martha", "Martina", "Maya", "Meike", "Melanie", "Melina", 
		"Melissa", "Meta", "Metha", "Mia", "Michaela", "Michelle", "Minna", 
		"Miriam", "Mirja", "Mirjam", "Monika", "Monique", "Nadin", "Nadine", 
		"Nadja", "Nancy", "Natalia", "Natalie", "Natascha", "Nathalie", "Neele", 
		"Nele", "Nicola", "Nicole", "Nikola", "Nina", "Olga", "Pamela", 
		"Patricia", "Patrizia", "Paula", "Peggy", "Petra", "Ramona", "Rebecca", 
		"Rebekka", "Regina", "Renate", "Rita", "Rosemarie", "Ruth", "Sabine", 
		"Sabrina", "Sandra", "Sara", "Sarah", "Saskia", "Sibylle", "Sigrid", 
		"Silke", "Silvia", "Simone", "Sina", "Sinah", "Sofia", "Sofie", 
		"Sonja", "Sophia", "Sophie", "Stefanie", "Steffi", "Stephanie", "Susan", 
		"Susann", "Susanne", "Svantje", "Svenja", "Svetlana", "Swantje", "Swenja", 
		"Swetlana", "Sybille", "Sylke", "Sylvia", "Sylwia", "Tamara", "Tania", 
		"Tanja", "Tatjana", "Tina", "Ulrike", "Ursula", "Uta", "Ute", 
		"Vanessa", "Vera", "Verena", "Veronica", "Veronika", "Victoria", "Viktoria", 
		"Viola", "Waltraud", "Waltraut", "Wera", "Wibke", "Wiebke", "Wilhelmine", 
		"Yasemin", "Yasmin", "Yvonne",
		
		"Adolf", "Albert", "Alexander", "Alfred", "André", "Andre", "Andreas", 
		"Arthur", "Artur", "August", "Axel", "Ben", "Benjamin", "Bernd", 
		"Björn", "Bruno", "Carl", "Carsten", "Christian", "Christoph", "Claus", 
		"Curt", "Daniel", "David", "Dennis", "Dieter", "Dirk", "Dominic", 
		"Dominik", "Elias", "Emil", "Eric", "Erich", "Erik", "Ernst", 
		"Erwin", "Fabian", "Felix", "Finn", "Florian", "Frank", "Franz", 
		"Friedrich", "Fritz", "Fynn", "Günter", "Günther", "Georg", "Gerd", 
		"Gerhard", "Gert", "Gustav", "Hans", "Harald", "Harri", "Harry", 
		"Heinrich", "Heinz", "Hellmut", "Helmut", "Helmuth", "Herbert", "Hermann", 
		"Holger", "Horst", "Hugo", "Ingo", "Jörg", "Jürgen", "Jacob", 
		"Jakob", "Jan", "Jannik", "Jens", "Joachim", "Johann", "Johannes", 
		"Jonas", "Jonathan", "Josef", "Joseph", "Julian", "Justin", "Kai", 
		"Karl", "Karl-Heinz", "Karlheinz", "Karsten", "Kay", "Kevin", "Klaus", 
		"Kristian", "Kurt", "Lars", "Lennard", "Lennart", "Leon", "Lothar", 
		"Louis", "Luca", "Lucas", "Ludwig", "Luis", "Luka", "Lukas", 
		"Lutz", "Maik", "Manfred", "Marc", "Marcel", "Marco", "Marcus", 
		"Mario", "Mark", "Marko", "Markus", "Martin", "Marvin", "Mathias", 
		"Matthias", "Max", "Maximilian", "Meik", "Michael", "Mike", "Moritz", 
		"Nick", "Niclas", "Nico", "Niels", "Niklas", "Niko", "Nils", 
		"Noah", "Norbert", "Olaf", "Ole", "Oliver", "Oscar", "Oskar", 
		"Otto", "Patrick", "Paul", "Peter", "Philip", "Philipp", "Phillipp", 
		"Rainer", "Ralf", "Ralph", "Reiner", "René", "Richard", "Robert", 
		"Rolf", "Rudolf", "Rudolph", "Sascha", "Sebastian", "Siegfried", "Simon", 
		"Stefan", "Steffen", "Stephan", "Sven", "Swen", "Thomas", "Thorsten", 
		"Tim", "Timm", "Tobias", "Tom", "Torsten", "Ulrich", "Uwe", 
		"Volker", "Walter", "Walther", "Werner", "Wilhelm", "Willi", "Willy", 
		"Wolfgang", "Yannic", "Yannick", "Yannik"
	};

	public static String[] nachnamen = {
		"Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner",  
		"Becker", "Schulz", "Hoffmann", "Schäfer", "Bauer", "Koch", "Richter",  
		"Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Braun", "Hofmann",  
		"Zimmermann", "Schmitt", "Hartmann", "Krüger", "Schmid", "Werner", "Lange",  
		"Schmitz", "Meier", "Krause", "Maier", "Lehmann", "Huber", "Mayer",  
		"Herrmann", "Köhler", "Walter", "König", "Schulze", "Fuchs", "Kaiser",  
		"Lang", "Weiß", "Peters", "Scholz", "Jung", "Möller", "Hahn",  
		"Keller", "Vogel", "Schubert", "Roth", "Frank", "Friedrich", "Beck",  
		"Günther", "Berger", "Winkler", "Lorenz", "Baumann", "Schuster", "Kraus",  
		"Böhm", "Simon", "Franke", "Albrecht", "Winter", "Ludwig", "Martin",  
		"Krämer", "Schumacher", "Vogt", "Jäger", "Stein", "Otto", "Groß",  
		"Sommer", "Haas", "Graf", "Heinrich", "Seidel", "Schreiber", "Ziegler",  
		"Brandt", "Kuhn", "Schulte", "Dietrich", "Kühn", "Engel", "Pohl",  
		"Horn", "Sauer", "Arnold", "Thomas", "Bergmann", "Busch", "Pfeiffer",  
		"Voigt", "Götz", "Seifert", "Lindner", "Ernst", "Hübner", "Kramer",  
		"Franz", "Beyer", "Wolff", "Peter", "Jansen", "Kern", "Barth",  
		"Wenzel", "Hermann", "Ott", "Paul", "Riedel", "Wilhelm", "Hansen",  
		"Nagel", "Grimm", "Lenz", "Ritter", "Bock", "Langer", "Kaufmann",  
		"Mohr", "Förster", "Zimmer", "Haase", "Lutz", "Kruse", "Jahn",  
		"Schumann", "Fiedler", "Thiel", "Hoppe", "Kraft", "Michel", "Marx",  
		"Fritz", "Arndt", "Eckert", "Schütz", "Walther", "Petersen", "Berg",  
		"Schindler", "Kunz", "Reuter", "Sander", "Schilling", "Reinhardt", "Frey",  
		"Ebert", "Böttcher", "Thiele", "Gruber", "Schramm", "Hein", "Bayer",  
		"Fröhlich", "Voß", "Herzog", "Hesse", "Maurer", "Rudolph", "Nowak",  
		"Geiger", "Beckmann", "Kunze", "Seitz", "Stephan", "Büttner", "Bender",  
		"Gärtner", "Bachmann", "Behrens", "Scherer", "Adam", "Stahl", "Steiner",  
		"Kurz", "Dietz", "Brunner", "Witt", "Moser", "Fink", "Ullrich",  
		"Kirchner", "Löffler", "Heinz", "Schultz", "Ulrich", "Reichert", "Schwab",  
		"Breuer", "Gerlach", "Brinkmann", "Göbel", "Blum", "Brand", "Naumann",  
		"Stark", "Wirth", "Schenk", "Binder", "Körner", "Schlüter", "Rieger",  
		"Urban", "Böhme", "Jakob", "Schröter", "Krebs", "Wegner", "Heller",  
		"Kopp", "Link", "Wittmann", "Unger", "Reimann", "Ackermann", "Hirsch",  
		"Schiller", "Döring", "May", "Bruns", "Wendt", "Wolter", "Menzel",  
		"Pfeifer", "Sturm", "Buchholz", "Rose", "Meißner", "Janssen", "Bach",  
		"Engelhardt", "Bischoff", "Bartsch", "John", "Kohl", "Kolb", "Münch",  
		"Vetter", "Hildebrandt", "Renner", "Weiss", "Kiefer", "Rau", "Hinz",  
		"Wilke", "Gebhardt", "Siebert", "Baier", "Köster", "Rohde", "Will",  
		"Fricke", "Freitag", "Nickel", "Reich", "Funk", "Linke", "Keil",  
		"Hennig", "Witte", "Stoll", "Schreiner", "Held", "Noack", "Brückner",  
		"Decker", "Neubauer", "Westphal", "Heinze", "Baum", "Schön", "Wimmer",  
		"Marquardt", "Stadler", "Schlegel", "Kremer", "Ahrens", "Hammer", "Röder",  
		"Pieper", "Kirsch", "Fuhrmann", "Henning", "Krug", "Popp", "Conrad",  
		"Karl", "Krieger", "Mann", "Wiedemann", "Lemke", "Erdmann", "Mertens",  
		"Heß", "Esser", "Hanke", "Strauß", "Miller", "Berndt", "Konrad",  
		"Jacob", "Philipp", "Metzger", "Henke", "Wiese", "Hauser", "Dittrich",  
		"Albert", "Klose", "Bader", "Herbst", "Henkel", "Kröger", "Wahl",  
		"Bartels", "Harms", "Fritsch", "Adler", "Großmann", "Burger", "Schrader",  
		"Probst", "Martens", "Baur", "Burkhardt", "Hess", "Mayr", "Nolte",  
		"Heine", "Kuhlmann", "Klaus", "Kühne", "Kluge", "Bernhardt", "Blank",  
		"Hamann", "Steffen", "Brenner", "Rauch", "Reiter", "Preuß", "Jost",  
		"Wild", "Hummel", "Beier", "Krauß", "Lindemann", "Herold", "Christ",  
		"Niemann", "Funke", "Haupt", "Janßen", "Vollmer", "Straub", "Strobel",  
		"Wiegand", "Merz", "Haag", "Holz", "Knoll", "Zander", "Rausch",  
		"Bode", "Beer", "Betz", "Anders", "Wetzel", "Hartung", "Glaser",  
		"Fleischer", "Rupp", "Reichel", "Lohmann", "Diehl", "Jordan", "Eder",  
		"Rothe", "Weis", "Heinemann", "Dörr", "Metz", "Kroll", "Freund",  
		"Wegener", "Hohmann", "Geißler", "Schüler", "Schade", "Raab", "Feldmann",  
		"Zeller", "Neubert", "Rapp", "Kessler", "Heck", "Meister", "Stock",  
		"Römer", "Seiler", "Altmann", "Behrendt", "Jacobs", "Mai", "Bär",  
		"Wunderlich", "Schütte", "Lauer", "Benz", "Weise", "Völker", "Sonntag",  
		"Bühler", "Gerber", "Kellner", "Bittner", "Schweizer", "Keßler", "Hagen",  
		"Wieland", "Born", "Merkel", "Falk", "Busse", "Gross", "Eichhorn",  
		"Greiner", "Moritz", "Forster", "Stumpf", "Seidl", "Scharf", "Hentschel",  
		"Buck", "Voss", "Hartwig", "Heil", "Eberhardt", "Oswald", "Lechner",  
		"Block", "Heim", "Steffens", "Weigel", "Pietsch", "Brandl", "Schott",  
		"Gottschalk", "Bertram", "Ehlers", "Fleischmann", "Albers", "Weidner", "Hiller",  
		"Seeger", "Geyer", "Jürgens", "Baumgartner", "Mack", "Schuler", "Appel",  
		"Pape", "Dorn", "Wulf", "Opitz", "Wiesner", "Hecht", "Moll",  
		"Gabriel", "Auer", "Engelmann", "Singer", "Neuhaus", "Giese", "Schütze",  
		"Geisler", "Ruf", "Heuer", "Noll", "Scheffler", "Sauter", "Reimer",  
		"Klemm", "Schaller", "Hempel", "Kretschmer", "Runge", "Springer", "Riedl",  
		"Steinbach", "Michels", "Barthel"
	};
	
	public static String[] vorwahlen = {
		"01511", "01512", "01514", "01515", "01516", "0160", "01609", 
		"0170", "0171", "0175", "01520", "01522", "01523", "01525", 
		"0162", "0172", "0173", "0174", "01521", "01529", "01573", 
		"01575", "01577", "01578", "0163", "0177", "0178", "01570", 
		"01579", "01590", "0176", "0179"
	};

}
